export const tiers = [
  {
    name: 'Standard',
    price: 15,
    description: 'Perfect for casual users',
    features: [
      '10 messages',
      'Access to all models',
      'One photo',
      'Email support',
    ],
    recommended: false,
    level: 'standard',
    currency: 'USD',
    color: 'blue',
  },
  {
    name: 'VIP',
    price: 20,
    description: 'Enhanced experience for enthusiasts',
    features: [
      '30 messages',
      'Access to all models',
      'Three photos',
      'Priority email support',
      'Access to premium videos',
    ],
    recommended: true,
    level: 'vip',
    currency: 'USD',
    color: 'amber',
  },
  {
    name: 'VVIP',
    price: 50,
    description: 'Ultimate experience for collectors',
    features: [
      'Unlimited messages',
      'Access to all models',
      'Access to 2 premium videos',
      'Access to limited edition content',
      'Chances of winning collectible items',
      '5 photos',
      '24/7 priority support',
    ],
    recommended: false,
    level: 'vvip',
    currency: 'USD',
    color: 'purple',
  },
];
